version: '3.8'
services:
  web:
    build: .
    ports:
      - '8080:3000'
    environment:
      - NODE_ENV=production
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: